# For binary mask & instance contour prediction.
# All other configurations are set by default. If you want to add new config options,
# please modify ../connectomics/config/config.py
# 30x8x8 nm in (z,y,x), 1000x4096x4096 voxel
SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 16
MODEL:
  ARCHITECTURE: 'unet_residual_3d' # 'unet_residual_3d' for res-unet-r  and 'rsunet' for res-unet-h
  FILTERS: [28, 36, 48, 64, 80]
  INPUT_SIZE: [32, 256, 256]
  OUTPUT_SIZE: [32, 256, 256]
  IN_PLANES: 1
  OUT_PLANES: 2
  LOSS_OPTION: [['DiceLoss', 'WeightedBCE'], ['DiceLoss', 'WeightedBCE']]
  LOSS_WEIGHT: [[0, 1], [0, 1]]
#  LOSS_OPTION: [['WeightedBCE'], ['WeightedBCE']]
#  LOSS_WEIGHT: [[1], [1]]
  TARGET_OPT: ['0','4-2-1'] # Multi-task learning: binary mask, instance segmentation
  WEIGHT_OPT: [['1'],['1']]
  SAVE_PATH: 'outputs/exp_3/dataset_output'
DATASET:
  IMAGE_NAME: 'training.tif' # default 'configs/MitoEM/im_train_rat.json'
  LABEL_NAME: 'training_instance_groundtruth.tif' # default 'configs/MitoEM/mito_train_rat.json'
  INPUT_PATH: '/braindat/lab/qic/data/PDAM/EM_DATA/EPFL/raw_data' # work container default '/braindat/lab/limx/MitoEM2021/CODE/HUMAN/rsunet_retrain_297000_v2/'
  # # inference: save model
  INFERENCE_PATH: '/braindat/lab/qic/data/PDAM/EM_DATA/EPFL/online' # default '/braindat/lab/limx/MitoEM2021/CODE/HUMAN/rsunet_retrain_297000_v2/'
  OUTPUT_PATH: 'outputs/exp_3/dataset_output'
  LOG_PATH: epfl/super/online
  PAD_SIZE: [16, 128, 128] # [16, 128, 128]  [0, 0, 0] # Mirror padding of big chunk 
  TRAIN_DO_CHUNK_TITLE: 0 # json file reading default 1
  TEST_DO_CHUNK_TITLE: 0
  TRAIN_SingleVolume: 0
  LABEL_EROSION: 1
  USE_LABEL_SMOOTH: False
  LABEL_SMOOTH: 0.1
  YMLY_PATH: 'configs/EPFL/super/epfl_online_2.yaml'
  EPFL: 0
  MitoH: 0
  MitoR: 0
AUGMENTOR:
  # Since the Lucchi dataset is isotropic (each voxel is cubic), we
  # apply flip augmentation also to x-z and z-y axes by default.
  CUTBLUR:
    DOWNSAMPLE_Z: True
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  BASE_LR: 1e-04
  ITERATION_STEP: 1 # How many iterations return loss once
  ITERATION_SAVE: 1000  # save model 1000
  EPOCH_PERIOD: 95000
  ITERATION_TOTAL: 200000 # total iteration
  SAMPLES_PER_BATCH: 2 # default 2
  TEST_BEGAIN_TESP: 30000  # 100000
  TRAIN_NAME: exp_3
INFERENCE:
  INPUT_SIZE: [32, 256, 256]
  OUTPUT_SIZE: [32, 256, 256]
  IMAGE_NAME: '/braindat/lab/qic/data/PDAM/EM_DATA/EPFL/raw_data/testing.tif'
  OUTPUT_PATH: 'outputs/exp_3/inference_output'
  OUTPUT_NAME: 'result.h5'
  PAD_SIZE:  [16, 128, 128]
  AUG_MODE: 'mean'
  AUG_NUM: 4
  STRIDE: [16, 128, 128] # [16, 128, 128]
  SAMPLES_PER_BATCH: 48
