AUGMENTOR:
  CUTBLUR:
    DOWNSAMPLE_Z: true
    DOWN_RATIO_MAX: 8.0
    DOWN_RATIO_MIN: 2.0
    ENABLED: true
    LENGTH_RATIO: 0.4
    P: 0.5
  CUTNOISE:
    ENABLED: true
    LENGTH_RATIO: 0.4
    P: 0.75
    SCALE: 0.3
  ELASTIC:
    ALPHA: 16.0
    ENABLED: true
    P: 0.75
    SIGMA: 4.0
  FLIP:
    DO_ZTRANS: 0
    ENABLED: true
    P: 1.0
  GRAYSCALE:
    ENABLED: true
    P: 0.75
  MISALIGNMENT:
    DISPLACEMENT: 16
    ENABLED: true
    P: 0.5
    ROTATE_RATIO: 0.5
  MISSINGPARTS:
    ENABLED: true
    P: 0.9
  MISSINGSECTION:
    ENABLED: true
    NUM_SECTION: 2
    P: 0.5
  MOTIONBLUR:
    ENABLED: true
    KERNEL_SIZE: 11
    P: 0.5
    SECTIONS: 2
  RESCALE:
    ENABLED: true
    P: 0.5
  ROTATE:
    ENABLED: true
    P: 0.5
  SMOOTH: true
DATASET:
  DATA_CHUNK_ITER: 1000
  DATA_CHUNK_NUM:
  - 1
  - 1
  - 1
  DATA_CHUNK_NUM_IND: []
  DATA_CHUNK_STRIDE: true
  DATA_INVALID_THRES:
  - 0
  - 0
  DATA_SCALE:
  - 1.0
  - 1.0
  - 1.0
  DO_2D: false
  EPFL: 1
  IMAGE_NAME: training.tif
  INFERENCE_PATH: /braindat/lab/qic/data/PDAM/EM_DATA/EPFL/online/blend
  INPUT_PATH: /data/chenqi/MitoEM2021/EPFL/raw_data
  IS_ISOTROPIC: false
  Kasthuri: 0
  LABEL_BINARY: false
  LABEL_EROSION: 1
  LABEL_MAG: 0
  LABEL_NAME: training_instance_groundtruth.tif
  LABEL_SMOOTH: 0.1
  LOG_PATH: epfl/blend/online
  MitoH: 0
  MitoR: 0
  OUTPUT_PATH: outputs/exp_1/dataset_output
  PAD_SIZE:
  - 16
  - 128
  - 128
  PRE_LOAD_DATA:
  - null
  - null
  - null
  REJECT_SAMPLING:
    AFTER_AUG: false
    P: 0.95
    SIZE_THRES: -1
  SCALE_FACTOR:
  - 2
  - 3
  - 3
  TEST_DO_CHUNK_TITLE: 0
  TRAIN_DO_CHUNK_TITLE: 0
  TRAIN_SingleVolume: 0
  USE_LABEL_SMOOTH: false
  YMLY_PATH: configs/EPFL/blend/epfl_online.yaml
INFERENCE:
  AUG_MODE: mean
  AUG_NUM: 4
  BLENDING: gaussian
  DO_3D: true
  DO_EVAL: true
  IMAGE_NAME: /braindat/lab/qic/data/PDAM/EM_DATA/EPFL/raw_data/testing.tif
  INPUT_PATH: ''
  INPUT_SIZE:
  - 32
  - 256
  - 256
  MODEL_OUTPUT_ID:
  - null
  OUTPUT_NAME: result.h5
  OUTPUT_PATH: outputs/exp_1/inference_output
  OUTPUT_SIZE:
  - 32
  - 256
  - 256
  PAD_SIZE:
  - 16
  - 128
  - 128
  SAMPLES_PER_BATCH: 48
  STRIDE:
  - 16
  - 128
  - 128
  TEST_ID: 0
  TEST_NUM: 1
MODEL:
  ACT_MODE: elu
  ARCHITECTURE: unet_residual_3d
  ATTENTION: squeeze_excitation
  BACKBONE: resnet
  BLOCKS:
  - 2
  - 2
  - 2
  - 2
  BLOCK_TYPE: residual
  DEPLOY_MODE: false
  EMBEDDING: 1
  EXACT: true
  FILTERS:
  - 28
  - 36
  - 48
  - 64
  - 80
  FINETUNE: ''
  HEAD_DEPTH: 1
  INPUT_SIZE:
  - 32
  - 256
  - 256
  IN_PLANES: 1
  ISOTROPY:
  - false
  - false
  - false
  - true
  - true
  KERNEL_SIZES:
  - 3
  - 3
  - 5
  - 3
  - 3
  LOSS_OPTION:
  - - DiceLoss
    - WeightedBCE
  - - DiceLoss
    - WeightedBCE
  LOSS_WEIGHT:
  - - 0
    - 1
  - - 0
    - 1
  NORM_MODE: bn
  OUTPUT_ACT: sigmoid
  OUTPUT_SIZE:
  - 32
  - 256
  - 256
  OUT_PLANES: 2
  PAD_MODE: replicate
  POOLING_LAYER: false
  PRE_MODEL: ''
  PRE_MODEL_ITER: 0
  PRE_MODEL_LAYER: ''
  PRE_MODEL_LAYER_SELECT: -1
  REGU_OPT: []
  REGU_WEIGHT: []
  SAVE_PATH: outputs/exp_1/dataset_output
  SIZE_MATCH: true
  TARGET_OPT:
  - '0'
  - 4-2-1
  WEIGHT_OPT:
  - - '1'
  - - '1'
MONITOR:
  ITERATION_NUM:
  - 10
  - 50
  LOG_OPT:
  - 1
  - 1
  - 0
  VIS_OPT:
  - 0
  - 8
SOLVER:
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 1.0
  CLIP_GRADIENTS:
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    ENABLED: false
    NORM_TYPE: 2.0
  EPOCH_PERIOD: 200000
  GAMMA: 0.1
  ITERATION_RESTART: false
  ITERATION_SAVE: 1000
  ITERATION_STEP: 1
  ITERATION_TOTAL: 200000
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MOMENTUM: 0.9
  SAMPLES_PER_BATCH: 2
  STEPS:
  - 80000
  - 90000
  TEST_BEGAIN_TESP: 30000
  TRAIN_NAME: exp_1
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0
  WEIGHT_DECAY_NORM: 0.0
SYSTEM:
  NUM_CPUS: 16
  NUM_GPUS: 2
  ROOTDIR: ''
